#!/usr/bin/env bash
# A script that redirects the user to moved permenantly

# Update the package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow HTTP traffic in the firewall (assuming you have UFW configured)
sudo ufw allow 'Nginx HTTP'

# Create an HTML file with the desired content
echo "Uganda_Is" | sudo tee /var/www/html/index.html

# Edit the Nginx default site configuration to add the redirect rule
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me 
https://www.youtube.com/watch?v=QH2-TGUlwu4/
 permanent;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart 
