#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP response header.

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom Nginx configuration file
echo "add_header X-Served-By \$hostname;" | sudo tee /etc/nginx/conf.d/custom_response_header.conf

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply the changes
sudo systemctl reload nginx
