#!/usr/bin/env bash
# this installs loadbalancer and configure HAproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get install -y haproxy=2.0.\*

echo "ENABLED=1" > /etc/default/haproxy
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
echo "
   listen load_balancer
   bind *:80
   balance roundrobin
   mode http
   option httpclose
   option forwardfor
   server 344195-web-01 54.237.227.206:80 check
   server 344195-web-02 34.229.49.26:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start

