#!/usr/bin/env bash
# it display a list of currently running processes
# shows all processes,for all users, including
# those which might not have a TTY
# display in a user-oriented format
# Shows process hierarchy

ps -auxf
